# Site settings
title: 学习，实践，分享
email: sunshareall0709@aliyun.com
description: > # this means to ignore newlines until "baseurl:"
  健康生活
  积极工作
  不断尝试，做正确的事
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://sunshare.github.io" # the base hostname & protocol for your site
# twitter_username: NONE
github_username:  sunshare

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
